language: python
python: 3.5
sudo: true
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=py35-nodeps
    - TOXENV=mypy
    - TOXENV=docs

addons:
    apt:
        packages:
            - python-numpy
            - python-scipy
            - libatlas-base-dev
            - liblapack-dev
            - gfortran

before_install:
    - sudo apt-get -qq update
    - if [[ "$TOXENV" != "py35-nodeps" ]]; then sudo apt-get install graphviz; fi

install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
